name: deploy-to-oss

on:
  push:
    branches:
      - master
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: yarn install
        uses: bahmutov/npm-install@v1

      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
